init:
  - git config --global core.autocrlf input
 
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
  - cmd: build.cmd
  - dotnet build "src\CommandLine" -c Release
after_build:
  - dotnet pack "src\CommandLine" -c Release --output artifacts
test: off
version: 0.0.1.{build}
artifacts:
  - path: artifacts\CommandLine.2.0.275.nupkg
    name: CommandLine.2.0.275
