init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
after_build:
  - nuget pack nuget\CommandLine.nuspec
test: off
version: 0.0.1.{build}
artifacts:
  - path: nuget\CommandLine.2.0.275.nupkg
    name: CommandLine.2.0.275
